FROM golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /app/bin/api ./services/api

FROM alpine:3.19

WORKDIR /app

COPY --from=builder /app/bin/api ./api
COPY configs ./configs

EXPOSE 8080

CMD ["./api"]