port: "8080"
salt: "fasdfasdfasdf"
db:
    username: "postgres"
    host: "db"
    port: "5432"
    dbname: "microblog"
    sslmode: "disable"
    password: "qwerty"

kafka:
    brokers:
        - "kafka:9092"
    likes_topic: "likes"
    client_id: "microblog-api"